### PR TITLE
5.6.36 FIXED Memory fixes

### PR DESCRIPTION
**Pull request by sgorpi**
running CtrlrX with valgrind while opening a panel etc, and parsing the output, there were a few more memory issues to solve. This PR addresses them.
This also uncovered a recursive 'setOwned' in `Source/UIComponents/CtrlrComponents/Groups/CtrlrGroup.cpp` that is now prevented.

I've also compared it to the branch of @dnaldoog  . Mostly no conflicts except maybe some space vs tab issue*.
But there is one set of files to watch out for:
- Source/UIComponents/CtrlrPropertyEditors/CtrlrPropertyComponent.cpp  <-- this overlaps with the branch from @dnaldoog ..., depending on who merges first: please follow the new pattern of not creating a `new StringArray`/`new Array` for `possibleChoices` and `possibleValues`, but call .clear(); on both of them to prevent memory leaks. (Towards the future, we best use std::unique_ptr or std::shared_ptr instead of 'new' directly, to prevent memory leaks.)
- Source/UIComponents/CtrlrPropertyEditors/CtrlrPropertyComponent.h changed from pointer to normal object

*) with respect to the spaces vs tabs issue: You guys could consider using [clang-format](https://clang.llvm.org/docs/ClangFormat.html) with some  [style](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) of your choice. Most editors/IDEs have some form of clang-format integration. Having it format for you automatically on file save or paste is ideal to keep it consistent.

### CODE REVIEW

**Comment by dnaldoog** [comment]
> *) with respect to the spaces vs tabs issue: You guys could consider using [clang-format](https://clang.llvm.org/docs/ClangFormat.html) with some [style](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) of your choice. Most editors/IDEs have some form of clang-format integration. Having it format for you automatically on file save or paste is ideal to keep it consistent.

I think I now have this set up in Visual Studio Code in Windows/Linux - thanks.

**Comment by damiensellier** [comment]
There's a mix of formating every IDE brought along the way.
I try to keep it as close as it was in the first place but it's not easy with xcode vs visual studio. tabulations should be 4 spaces etc

I'll add a .clang-format file with pointer/reference alignment and tabs vs. spaces

something like this should enforce the style across all IDE and stays with projucer as well as with cmake : 
```

---
# Access the base style (LLVM is standard, or you can use Google/Chromium)
BasedOnStyle: LLVM

# Enforce your preferred indentation (e.g., Spaces instead of Tabs)
UseTab: Never
IndentWidth: 4
TabWidth: 4

# --- THE POINTER/REFERENCE ALIGNMENT FIX ---
# This controls where the * and & sit. 
# Options: Left (int* p), Right (int *p), Middle (int * p)
PointerAlignment: Left

# Keep the rest of the file clean
ColumnLimit: 100
FixNamespaceComments: true
...
```

Formating in .h files is a bit weird to me especially the double tabbing thing, I don't know what style Roman Kubiak used for that, I do copy/paste lines to keep the formating identical in xcode or it's not preserved even with 4 spaces indents.

**Comment by damiensellier** [comment]
Hi guys, I just opened [an issue about that IDE formating problem](https://github.com/damiensellier/CtrlrX/issues/288) not to disturb the discussion about @sgorpi PR related to memory leaks fixes.

-> https://github.com/damiensellier/CtrlrX/issues/288


Thx

**Comment by damiensellier** [comment]
UPDATED on 2026.07.16 for CtrlrX 5.6.36 commit 0bea8c4ceaa70e2b12f9e9c00cdeec453318b0d3

Thanks a lot Hedde!

Damien

**Comment by damiensellier** [comment]
@sgorpi The compilation failed so I had to revert value types to raw pointers to make it work with JUCE 6.0.8

SEE : commit 0491e69ec423b408216bc445f72140b0b3c7a51c

**Comment by sgorpi** [comment]
Ok, I'll have a look after the holidays then. I suspect it has to do with the bullets after "But there is one set of files to watch out for:" 😄 at least the other stuff will already fix quite a few leaks. Cheers!
